import type { Parser } from '@sveltekit-i18n/base';

import type { Entry, Skipped } from './types.js';

const KINDS: Record<Parser.ParamKind, string> = {
  unknown: 'unknown',
  string: 'string',
  number: 'number',
  boolean: 'boolean',
  // What `Intl.DateTimeFormat` accepts, which is what a date parameter reaches.
  date: 'Date | number',
  // The rich-text callback shape a tag parameter is called with.
  function: '(chunks: string[]) => string',
};

// A line terminator would end the literal, so it is escaped as well.
const quote = (name: string): string => `'${name.split('\\').join('\\\\').split("'").join("\\'").split('\n').join('\\n').split('\r').join('\\r')}'`;

// A namespace is any string, and a template type reads a backtick and `${` too.
// A raw line terminator would be normalized, a carriage return read as a line
// feed, so both are escaped.
const template = (text: string): string => text.split('\\').join('\\\\').split('`').join('\\`').split('${').join('\\${').split('\n').join('\\n').split('\r').join('\\r');

const SKIPPED_NOTE = '  /** Not read: its loader cannot run outside the app. */';

const skippedMember = ({ namespace, whole }: Skipped): string => (
  whole ? `  ${quote(namespace)}: any;` : `  [key: \`${template(namespace)}.\${string}\`]: any;`
);

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

// Neither a key nor a parameter name is necessarily an identifier, so quoting
// is the default; a name that reads fine unquoted is left alone.
const property = (name: string, optional: boolean): string => (
  `${IDENTIFIER.test(name) ? name : quote(name)}${optional ? '?' : ''}`
);

const typeOf = ({ kind }: Parser.ParamSpec): string => {
  const kinds = kind === undefined ? ['unknown' as const] : [kind].flat();
  const named = [...new Set(kinds.map((one) => (Object.hasOwn(KINDS, one) ? KINDS[one] : 'unknown')))];

  // A union of function types needs parentheses around each member; wrapping
  // every member is the same type and one rule instead of two.
  return named.length > 1 ? named.map((one) => `(${one})`).join(' | ') : named[0];
};

const MAX_COMMENT = 120;

// `*/` would close the comment; the escape renders as itself.
const comment = (text: string): string => text.split('*/').join('*\\/');

// A translation value is arbitrary data, and JSON holds most of it — not a
// BigInt, not a cycle. What it cannot hold goes undescribed.
const json = (value: unknown): string | undefined => {
  try {
    return JSON.stringify(value);
  } catch {
    return undefined;
  }
};

/**
 * The reference value, one line, short enough to read in a completion popup.
 * A non-string is shown as JSON.
 */
const describe = (value: unknown): string | undefined => {
  const text = typeof value === 'string' ? value : json(value);

  if (!text) return undefined;

  const flat = text.split(/\s+/).join(' ').trim();

  return comment(flat.length > MAX_COMMENT ? `${flat.slice(0, MAX_COMMENT - 1)}…` : flat);
};

const condition = ({ when }: Parser.ParamSpec): string | undefined => (
  when?.length ? comment(`used when ${when.map(({ param, branch }) => `${param} is \`${branch}\``).join(' and ')}`) : undefined
);

const payloadOf = (params: readonly Parser.ParamSpec[], indent: string): string => {
  // A parameter under a selector branch is annotated rather than discriminated:
  // a message with several nested selectors would otherwise emit a union whose
  // size is the product of their branches, and the caller pays for it on every
  // keystroke.
  const properties = params.reduce<string[]>((acc, param) => {
    const note = condition(param);
    const line = `${indent}  ${property(param.name, !!param.optional)}: ${typeOf(param)};`;

    return [...acc, ...(note ? [`${indent}  /** ${note} */`] : []), line];
  }, []);

  return `{\n${properties.join('\n')}\n${indent}}`;
};

const valueOf = ({ params }: Entry, indent: string): string => {
  // No extractor: the slot stays unchecked. `never` would reject a legal call,
  // `any` narrows the key and leaves the payload alone.
  if (params === null) return 'any';

  // `never` is how base spells a message that takes no payload – the argument
  // may be omitted, or passed as an explicit `undefined`.
  return params.length ? payloadOf(params, indent) : 'never';
};

export type Artifact = {
  /** The generated declarations, or the placeholder when `entries` is absent. */
  contents: string;
  count: number;
};

const BANNER = [
  '// Generated by @sveltekit-i18n/typegen. Do not edit, and do not commit.',
].join('\n');

/**
 * The placeholder written before anything that can throw. An EMPTY interface
 * degrades to plain `string` keys, so a project compiles before the first
 * generation and after a failed one; an index signature would look equivalent
 * and instead disable narrowing for good, since it survives the declaration
 * merge that the real artifact arrives by.
 */
export const placeholder = (): string => [
  BANNER,
  '',
  'interface TranslationSchema {}',
  '',
].join('\n');

/**
 * The generated declarations. Keys are sorted so that an unchanged catalogue
 * produces unchanged bytes and the write can be skipped.
 */
export const emit = (entries: readonly Entry[], referenceLocale: string, skipped: readonly Skipped[] = []): Artifact => {
  const sorted = [...entries].sort((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0));
  const keys = new Set(sorted.map(({ key }) => key));

  const members = sorted.reduce<string[]>((acc, entry) => {
    const note = describe(entry.value);

    return [...acc, ...(note ? [`  /** ${note} */`] : []), `  ${quote(entry.key)}: ${valueOf(entry, '  ')};`];
  }, []);

  // A pattern member keeps the schema closed: every other key still narrows,
  // and a key the reference did deliver keeps its own payload.
  const open = [...skipped]
    .filter(({ namespace, whole }) => !whole || !keys.has(namespace))
    .sort((a, b) => (a.namespace < b.namespace ? -1 : a.namespace > b.namespace ? 1 : 0))
    .flatMap((one) => [SKIPPED_NOTE, skippedMember(one)]);

  const contents = [
    BANNER,
    `// Reference locale: ${referenceLocale}`,
    '',
    members.length || open.length ? `interface TranslationSchema {\n${[...members, ...open].join('\n')}\n}` : 'interface TranslationSchema {}',
    '',
  ].join('\n');

  return { contents, count: sorted.length };
};
