import type { Parser } from '@sveltekit-i18n/base';

import type { Entry, Skipped } from './types.js';

const KINDS: Record<Parser.ParamKind, string> = {
  unknown: 'unknown',
  string: 'string',
  number: 'number',
  boolean: 'boolean',
  // What `Intl.DateTimeFormat` accepts, which is what a date parameter reaches.
  date: 'Date | number',
  // The rich-text callback shape a tag parameter is called with.
  function: '(chunks: string[]) => string',
};

// A line terminator would end the literal, so it is escaped as well.
const quote = (name: string): string => `'${name.split('\\').join('\\\\').split("'").join("\\'").split('\n').join('\\n').split('\r').join('\\r')}'`;

// A namespace is any string, and a template type reads a backtick and `${` too.
// A raw line terminator would be normalized, a carriage return read as a line
// feed, so both are escaped.
const template = (text: string): string => text.split('\\').join('\\\\').split('`').join('\\`').split('${').join('\\${').split('\n').join('\\n').split('\r').join('\\r');

const SKIPPED_NOTE = '  /** Not read: its loader cannot run outside the app. */';

const skippedMember = ({ namespace, whole }: Skipped): string => (
  whole ? `  ${quote(namespace)}: any;` : `  [key: \`${template(namespace)}.\${string}\`]: any;`
);

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

// Neither a key nor a parameter name is necessarily an identifier, so quoting
// is the default; a name that reads fine unquoted is left alone.
const property = (name: string, optional: boolean): string => (
  `${IDENTIFIER.test(name) ? name : quote(name)}${optional ? '?' : ''}`
);

const typeOf = ({ kind }: Parser.ParamSpec): string => {
  const kinds = kind === undefined ? ['unknown' as const] : [kind].flat();
  const named = [...new Set(kinds.map((one) => (Object.hasOwn(KINDS, one) ? KINDS[one] : 'unknown')))];

  // A union of function types needs parentheses around each member; wrapping
  // every member is the same type and one rule instead of two.
  return named.length > 1 ? named.map((one) => `(${one})`).join(' | ') : named[0];
};

const MAX_COMMENT = 120;

// `*/` would close the comment; the escape renders as itself.
const comment = (text: string): string => text.split('*/').join('*\\/');

// A translation value is arbitrary data, and JSON holds most of it — not a
// BigInt, not a cycle. What it cannot hold goes undescribed.
const json = (value: unknown): string | undefined => {
  try {
    return JSON.stringify(value);
  } catch {
    return undefined;
  }
};

/**
 * The reference value, one line, short enough to read in a completion popup.
 * A non-string is shown as JSON.
 */
const describe = (value: unknown): string | undefined => {
  const text = typeof value === 'string' ? value : json(value);

  if (!text) return undefined;

  const flat = text.split(/\s+/).join(' ').trim();

  return comment(flat.length > MAX_COMMENT ? `${flat.slice(0, MAX_COMMENT - 1)}…` : flat);
};

const condition = ({ when }: Parser.ParamSpec): string | undefined => (
  when?.length ? comment(`used when ${when.map(({ param, branch }) => `${param} is \`${branch}\``).join(' and ')}`) : undefined
);

const payloadOf = (params: readonly Parser.ParamSpec[], indent: string): string => {
  // A parameter under a selector branch is annotated rather than discriminated:
  // a message with several nested selectors would otherwise emit a union whose
  // size is the product of their branches, and the caller pays for it on every
  // keystroke.
  const properties = params.flatMap((param) => {
    const note = condition(param);
    const line = `${indent}  ${property(param.name, !!param.optional)}: ${typeOf(param)};`;

    return [...(note ? [`${indent}  /** ${note} */`] : []), line];
  });

  return `{\n${properties.join('\n')}\n${indent}}`;
};

const valueOf = ({ params }: Entry, indent: string): string => {
  // No extractor: the slot stays unchecked. `never` would reject a legal call,
  // `any` narrows the key and leaves the payload alone.
  if (params === null) return 'any';

  // `never` is how base spells a message that takes no payload – the argument
  // may be omitted, or passed as an explicit `undefined`.
  return params.length ? payloadOf(params, indent) : 'never';
};

export type Artifact = {
  /** The generated declarations, or the placeholder when `entries` is absent. */
  contents: string;
  count: number;
};

const BANNER = [
  '// Generated by @sveltekit-i18n/typegen. Do not edit, and do not commit.',
].join('\n');

/** A segment of a key, and what lies at its path: the key itself, an open namespace, the segments below. */
type Segment = { key?: string; open?: boolean; next?: Map<string, Segment> };

const byCodeUnit = (a: string, b: string): number => (a < b ? -1 : a > b ? 1 : 0);

/**
 * The keys nested by segment, split on every dot as the typed-access extension
 * splits them, one interface per level, numbered in preorder. A segment is
 * consumer data, so the levels are maps: a plain object would read
 * `constructor` as present and route `__proto__` to its prototype. Below an
 * open namespace each node is a key too, as the pattern reads it. Built
 * without recursion, since a key can hold thousands of segments.
 */
const levelsOf = (literals: readonly string[], namespaces: readonly string[]): string[] => {
  const root: Segment = { next: new Map() };
  const at = (path: string): Segment => path.split('.').reduce((node, name) => {
    node.next ??= new Map();

    const child = node.next.get(name) ?? {};

    node.next.set(name, child);

    return child;
  }, root);

  for (const key of literals) at(key).key = key;
  for (const namespace of namespaces) at(namespace).open = true;

  type Level = { next: Map<string, Segment>; prefix: string; open: boolean; segments: string[] };

  const order: Level[] = [];
  const names = new Map<Map<string, Segment>, string>();
  const stack: Omit<Level, 'segments'>[] = [{ next: root.next!, prefix: '', open: false }];

  while (stack.length) {
    const level = stack.pop()!;
    const segments = [...level.next.keys()].sort(byCodeUnit);

    names.set(level.next, `Level${order.length}`);
    order.push({ ...level, segments });

    for (let index = segments.length - 1; index >= 0; index -= 1) {
      const node = level.next.get(segments[index])!;

      if (node.next) stack.push({ next: node.next, prefix: `${level.prefix}${segments[index]}.`, open: level.open || !!node.open });
    }
  }

  return order.map(({ next, prefix, open, segments }, index) => {
    const members = segments.map((segment) => {
      const node = next.get(segment)!;
      const key = open ? `${prefix}${segment}` : node.key;
      const parts = [
        ...(key === undefined ? [] : [`key: ${quote(key)}`]),
        ...(node.open ? ['open: true'] : []),
        ...(node.next ? [`next: ${names.get(node.next)}`] : []),
      ];

      return `      ${quote(segment)}: { ${parts.join('; ')} };`;
    });

    return members.length ? `    interface Level${index} {\n${members.join('\n')}\n    }` : `    interface Level${index} {}`;
  });
};

/** FNV-1a, as eight hex digits: stable across runs and platforms. */
const fingerprint = (text: string): string => {
  let hash = 0x811c9dc5;

  for (let index = 0; index < text.length; index += 1) hash = Math.imul(hash ^ text.charCodeAt(index), 0x01000193);

  return (hash >>> 0).toString(16).padStart(8, '0');
};

const union = (name: string, members: readonly string[]): string[] => (members.length
  ? [`      ${name}:`, ...members.map((member, index) => `        | ${member}${index === members.length - 1 ? ';' : ''}`)]
  : [`      ${name}: never;`]);

/**
 * Registers the schema with the core: on base 3.1 a config that states no
 * `schema` is typed by `SvelteKitI18n.Register`, and 3.0 ignores the block. A
 * declaration in a script, so it merges into the global namespace. `tree`
 * carries the keys nested by segment for the typed-access extension, and the
 * literal keys and patterns it was built from, apart, as the extension
 * compares them with the schema it types, so a key declared elsewhere is never
 * lost; the core reads none of it. The levels live in a namespace named after
 * that key set, so the levels of two artifacts in one program never merge.
 */
const register = (keys: readonly string[], patterns: readonly string[], levels: readonly string[]): string => {
  const namespace = `K${fingerprint([...keys, '', ...patterns].join('\n'))}`;

  return [
    'declare namespace SvelteKitI18n {',
    '  interface Register {',
    '    schema: TranslationSchema;',
    '    tree: {',
    ...union('keys', keys),
    ...union('patterns', patterns),
    `      next: Typegen.${namespace}.Level0;`,
    '    };',
    '  }',
    `  namespace Typegen.${namespace} {`,
    levels.join('\n'),
    '  }',
    '}',
  ].join('\n');
};

const REGISTER_EMPTY = register([], [], levelsOf([], []));

/**
 * The placeholder written before anything that can throw. An EMPTY interface,
 * registered as the artifact registers it, degrades to plain `string` keys, so
 * a project compiles before the first generation and after a failed one; an
 * index signature would look equivalent and instead disable narrowing for
 * good, since it survives the declaration merge that the real artifact arrives
 * by.
 */
export const placeholder = (): string => [
  BANNER,
  '',
  'interface TranslationSchema {}',
  '',
  REGISTER_EMPTY,
  '',
].join('\n');

/**
 * The generated declarations. Keys are sorted so that an unchanged catalogue
 * produces unchanged bytes and the write can be skipped.
 */
export const emit = (entries: readonly Entry[], referenceLocale: string, skipped: readonly Skipped[] = []): Artifact => {
  const sorted = [...entries].sort((a, b) => byCodeUnit(a.key, b.key));
  const keys = new Set(sorted.map(({ key }) => key));

  const members = sorted.flatMap((entry) => {
    const note = describe(entry.value);

    return [...(note ? [`  /** ${note} */`] : []), `  ${quote(entry.key)}: ${valueOf(entry, '  ')};`];
  });

  // A pattern member keeps the schema closed: every other key still narrows,
  // and a key the reference did deliver keeps its own payload.
  const unread = [...skipped]
    .filter(({ namespace, whole }) => !whole || !keys.has(namespace))
    .sort((a, b) => byCodeUnit(a.namespace, b.namespace));
  const open = unread.flatMap((one) => [SKIPPED_NOTE, skippedMember(one)]);
  const literals = [...keys, ...unread.filter(({ whole }) => whole).map(({ namespace }) => namespace)];
  const namespaces = unread.filter(({ whole }) => !whole).map(({ namespace }) => namespace);

  const contents = [
    BANNER,
    `// Reference locale: ${referenceLocale}`,
    '',
    members.length || open.length ? `interface TranslationSchema {\n${[...members, ...open].join('\n')}\n}` : 'interface TranslationSchema {}',
    '',
    register(literals.map(quote), namespaces.map((namespace) => `\`${template(namespace)}.\${string}\``), levelsOf(literals, namespaces)),
    '',
  ].join('\n');

  return { contents, count: sorted.length };
};
